# -*- coding: utf-8 -*-
"""Ahmed_week2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/123aR9sGuyddn4kFb0Iqi_BYz3xaZgwOw

Homework 2 by Shadman Ahmed

Write a while loop that asks the user for a fruit and replies "I like [the fruit]" (if the length of the name of the fruit is 5 or less letters) or "I do not like [the fruit]" (otherwise) and stops when the user enters "Stop".
"""

fruit = ""

while fruit != "Stop":
  fruit = input("Enter the name of a fruit or Stop (with a capital 'S') to quit.")
  if fruit == "Stop":
    print("Bye. I figured out the code >:)")
  elif len(fruit) <= 5:
    print("I like the fruit.")
  else:
    print("I don't like the fruit.")